### PR TITLE
[MRG] Fix `all_clean_contigs` target for short contigs

### LINKED ISSUE #186: KeyError in charcoal target `all_clean_contigs`
```
$ python -m charcoal run genbank_genomes.conf -j 1 all_clean_contigs
** read 361 provided lineages
** config file checks PASSED!
** from here on out, it's all snakemake...
Building DAG of jobs...
Updating job clean_contigs.
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       all_clean_contigs
        122     clean_contigs
        123
Select jobs to execute...

[Wed Jun  2 16:56:30 2021]
rule clean_contigs:
    input: /home/tereiter/github/2020-ibd/genbank_genomes/GCF_005845265.1_genomic.fna.gz, output.genbank_genomes/stage1/GCF_005845265.1_genomic.fna.gz.contigs-tax.json, output.genbank_genomes/stage1_hitlist.csv
    output: output.genbank_genomes/GCF_005845265.1_genomic.fna.gz.clean.fa.gz, output.genbank_genomes/GCF_005845265.1_genomic.fna.gz.dirty.fa.gz
    jobid: 1663
    wildcards: f=GCF_005845265.1_genomic.fna.gz

Activating conda environment: /home/tereiter/github/charcoal/.snakemake/conda/017135dd391ef3c0eb7f938c30cafcd9
loaded 58 contig assignments.
filtering GCF_005845265.1_genomic.fna.gz contigs at order
note, genome lineage is d__Bacteria;p__Firmicutes_A;c__Clostridia;o__Lachnospirales
Traceback (most recent call last):
  File "/home/tereiter/github/charcoal/.snakemake/conda/017135dd391ef3c0eb7f938c30cafcd9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/tereiter/github/charcoal/.snakemake/conda/017135dd391ef3c0eb7f938c30cafcd9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/tereiter/github/charcoal/charcoal/clean_genome.py", line 134, in <module>
    returncode = cmdline(sys.argv[1:])
  File "/home/tereiter/github/charcoal/charcoal/clean_genome.py", line 129, in cmdline
    return main(args)
  File "/home/tereiter/github/charcoal/charcoal/clean_genome.py", line 98, in main
    gather_info = contigs_d[record.name]
KeyError: 'NZ_SPHP01000055.1 Clostridium sp. 1001175st1 A10 strain 1001175st1_A10 NODE_55_length_2677_cov_60.1085, whole genome shotgun sequence'
[Wed Jun  2 16:56:36 2021]
Error in rule clean_contigs:
    jobid: 1663
    output: output.genbank_genomes/GCF_005845265.1_genomic.fna.gz.clean.fa.gz, output.genbank_genomes/GCF_005845265.1_genomic.fna.gz.dirty.fa.gz
    conda-env: /home/tereiter/github/charcoal/.snakemake/conda/017135dd391ef3c0eb7f938c30cafcd9
    shell:

        python -m charcoal.clean_genome             --genome /home/tereiter/github/2020-ibd/genbank_genomes/GCF_005845265.1_genomic.fna.gz             --hit-list output.genbank_genomes/stage1_hitlist.csv             --contigs-json output.genbank_genomes/stage1/GCF_005845265.1_genomic.fna.gz.contigs-tax.json             --clean output.genbank_genomes/GCF_005845265.1_genomic.fna.gz.clean.fa.gz --dirty output.genbank_genomes/GCF_005845265.1_genomic.fna.gz.dirty.fa.gz

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job clean_contigs since they might be corrupted:
output.genbank_genomes/GCF_005845265.1_genomic.fna.gz.clean.fa.gz, output.genbank_genomes/GCF_005845265.1_genomic.fna.gz.dirty.fa.gz
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/tereiter/github/charcoal/.snakemake/log/2021-06-02T165625.652902.snakemake.log
Error in snakemake invocation: Command '['snakemake', '-s', '/home/tereiter/github/charcoal/charcoal/Snakefile', '--use-conda', '-j', '1', '-j', '1', 'all_clean_contigs', '--configfile', '/home/tereiter/github/charcoal/charcoal/conf/defaults.conf', '/home/tereiter/github/charcoal/charcoal/conf/system.conf', 'genbank_genomes.conf']' returned non-zero exit status 1.
```

The offending line in `charcoal/clean_genome.py` has a comment indicating that this is an error stemming from an issue with the hitlist
```
for record in screed_iter:
        # note: if record.name is not in the contigs dictionary, that
        # means that the code that output the hitlist did something
        # wrong!
        gather_info = contigs_d[record.name]
```

The offending node listed above does not appear in `GCF_005845265.1_genomic.fna.gz.contigs-tax.json`

This error happened 122 times on 361 genomes that I ran it on...I'm not really sure where it's coming from yet

### PR DESCRIPTION
**Pull request by ctb**
Fixes #186.

It looks like the cause of https://github.com/dib-lab/charcoal/issues/186 is short contigs that don't have any hashes assigned to them. The initial set of changes in this PR fix the resulting issue and add a simple test.

### CODE REVIEW

**Comment by taylorreiter** [comment]
Oh that reason makes a lot of sense. Using this branch, I get the same error as I did in #186

**Comment by ctb** [comment]
On Thu, Jun 03, 2021 at 05:22:11PM -0700, Taylor Reiter wrote:
> Oh that reason makes a lot of sense. Using this branch, I get the same error as I did in #186

you will need to delete the tax .json files.

**Comment by taylorreiter** [comment]
woops yup works, thank you!

**Comment by ilikvlad** [comment]
Hello, 

user feedback: charcoal is now working smoothly on both short-read and long-read eukaryotic assemblies using this command:
`python -m charcoal run <config_file> -j 8 clean` 
and providing eukaryotic lineages like this: 
`<name_of_the_assembly>,d__Eukaryota`
It is very simple to use and efficient as run time for 9 eukaryotic genomes (around 240Mb) was only 2 hours, when using 8 threads. Also numbers of nucleotides, contigs and scaffolds match perfectly after decontaminating. 

Thank you and all the best, 

Vladislav

**Comment by ctb** [comment]
that's great to hear! please let us know as you evaluate the results, too!

**Comment by ilikvlad** [comment]
Sure, 

I tried to charocal non-decontaminated Illumina assemblies (megahit) and the results pretty much agree with previously done Blobtools results (in terms of similar percentage of contamination detected and proving mainly bacterial contamination, which was in our case pretty low ~3%). I also tried it on three previously decontaminated long-read assemblies (sourmash decontaminated) and in this case, for one assembly charcoal detected zero contamination and for the two others it was 0.001 % and 0.002 %.

**Pull request merged**
