### PR TITLE
[MRG] flatten db sigs for in contam code

### PR DESCRIPTION
**Pull request by taylorreiter**
Like #178, but for script `charcoal/contigs_list_contaminants.py`

### CODE REVIEW

**Comment by taylorreiter** [comment]
woops probably should have done this on a new branch...I'm pretty sure most of these changes are already in `latest`

**Comment by ctb** [comment]
> woops probably should have done this on a new branch...I'm pretty sure most of these changes are already in `latest`

I did a `git checkout tr-bugs; git pull origin latest; git push` and all seems well.

**Comment by ctb** [comment]
main question: does this new change need a test?

**Comment by taylorreiter** [comment]
@ctb now has a test with c7f608f :)

**Review by ctb — APPROVED** [review]

**Pull request merged**
