### PR TITLE
try evaluating GTDB contamination

### PR DESCRIPTION
**Pull request by ctb**
Taking a stab at #121!! This uses `search --containment` instead of `gather`, and removes identical matches, before doing its thang.

### CODE REVIEW

**Comment by ctb** [comment]
I've been running this on both "known contaminants" and good genomes. The results are intriguing. Some notes to self --

* entire genomes are removed because they have a few hashes that match something other than the primary lineage. We should probably have a threshold that refuses to decontaminate if the contamination is less than 5% of the sequence (or some similar threshold). That would eliminate most of the false positives in both the known contaminants and the good genomes!
* (that observation actually helps explain our LCA-based false positives...)
* based on these results, it's not clear that a match_rank of order is sufficiently stringent; there are a lot of messed up orders in GTDB :(.
* definitely want to switch to using only the gather method.

**Comment by ctb** [comment]
Some things that look like false positives due to order or class confusion w/clostridia etc --

```
GCF_000154285.1_genomic.fna.gz
GCA_900066905.1_genomic.fna.gz
GCF_900167505.1_genomic.fna.gz
GCF_002734245.1_genomic.fna.gz
GCA_002493965.1_genomic.fna.gz
GCA_002839205.1_genomic.fna.gz
GCF_000751555.1_genomic.fna.gz
GCA_002323775.1_genomic.fna.gz
```

Some things that look like true positives --

```
GCA_002721375.1_genomic.fna.gz
GCA_002730555.1_genomic.fna.gz
```

Can't tell for sure --

```
GCA_002499505.1_genomic.fna.gz
GCA_000762985.1_genomic.fna.gz
```

**Comment by ctb** [comment]
note to self: in gather reporting, aggregate gather to match rank.

**Comment by bluegenes** [comment]
> note to self: in gather reporting, aggregate gather to match rank.

would this be in charcoal, or as output of gather?

**Comment by ctb** [comment]
@bluegenes whoops missed this --

>would this be in charcoal, or as output of gather?

charcoal. sourmash doesn't have access to taxonomy for gather.

**Pull request merged**
